<a href="https://colab.research.google.com/github/missstechie/SDG-Classifier-MVP-/blob/main/SDG_Classifier(MVP).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [30]:
!pip install -q sentence-transformers pandas scikit-learn

In [31]:
from sentence_transformers import SentenceTransformer
from sklearn.metrics.pairwise import cosine_similarity
import pandas as pd

In [32]:
sdgs = {
    "SDG 1": "No poverty",
    "SDG 2": "Zero hunger",
    "SDG 3": "Good health and well-being",
    "SDG 4": "Quality education",
    "SDG 5": "Gender equality",
    "SDG 6": "Clean water and sanitation",
    "SDG 7": "Affordable and clean energy",
}

In [33]:
model = SentenceTransformer('all-MiniLM-L6-v2')

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

In [34]:
print(predict_sdg_top3("A mobile app that improves rural healthcare and education access"))

['SDG 4', 'SDG 1', 'SDG 7']

In [35]:
sdg_texts = list(sdgs.values())
sdg_embeddings = model.encode(sdg_texts)

In [36]:
def predict_sdg(text):
    preds_with_details = _predict_sdg_with_details(text)
    if preds_with_details:
        top_pred = preds_with_details[0]
        return (top_pred[0], top_pred[1]) # Return (sdg_code, sdg_description)
    return (None, None)

def predict_sdg_top3(text):
    preds_with_details = _predict_sdg_with_details(text)
    return [p[0] for p in preds_with_details] # Return list of sdg_codes

In [37]:
def predict_sdg(text):
    preds_with_details = _predict_sdg_with_details(text)
    if preds_with_details:
        top_pred = preds_with_details[0]
        return (top_pred[0], top_pred[1]) # Return (sdg_code, sdg_description)
    return (None, None)

def predict_sdg_top3(text):
    preds_with_details = _predict_sdg_with_details(text)
    return [p[0] for p in preds_with_details] # Return list of sdg_codes

In [38]:
test_text = "A mobile app that helps rural students access education"

print(predict_sdg(test_text))

('SDG 4', 'Quality education')

In [39]:
evaluate(df)

Project: Mobile health app for villages
Predicted Top 3:
  - SDG 3: Good health and well-being (Similarity: 0.2929)
  - SDG 1: No poverty (Similarity: 0.2344)
  - SDG 7: Affordable and clean energy (Similarity: 0.2256)
Actual: SDG 3
--- For accuracy calculation, checking against: ['SDG 3', 'SDG 1', 'SDG 7']
Project: Online education platform for students
Predicted Top 3:
  - SDG 4: Quality education (Similarity: 0.3690)
  - SDG 5: Gender equality (Similarity: 0.1421)
  - SDG 1: No poverty (Similarity: 0.0974)
Actual: SDG 4
--- For accuracy calculation, checking against: ['SDG 4', 'SDG 5', 'SDG 1']
Project: Clean drinking water system
Predicted Top 3:
  - SDG 6: Clean water and sanitation (Similarity: 0.7120)
  - SDG 7: Affordable and clean energy (Similarity: 0.2668)
  - SDG 4: Quality education (Similarity: 0.1540)
Actual: SDG 6
--- For accuracy calculation, checking against: ['SDG 6', 'SDG 7', 'SDG 4']
Project: Solar energy for rural homes
Predicted Top 3:
  - SDG 7: Affordable and clean energy (Similarity: 0.5092)
  - SDG 6: Clean water and sanitation (Similarity: 0.1359)
  - SDG 1: No poverty (Similarity: 0.1339)
Actual: SDG 7
--- For accuracy calculation, checking against: ['SDG 7', 'SDG 6', 'SDG 1']

Top-3 Accuracy: 1.0

In [40]:
data = {
    "project": [
        "Mobile health app for villages",
        "Online education platform for students",
        "Clean drinking water system",
        "Solar energy for rural homes"
    ],
    "actual_sdg": [
        "SDG 3",
        "SDG 4",
        "SDG 6",
        "SDG 7"
    ]
}

df = pd.DataFrame(data)
df

                                  project actual_sdg
0          Mobile health app for villages      SDG 3
1  Online education platform for students      SDG 4
2             Clean drinking water system      SDG 6
3            Solar energy for rural homes      SDG 7

In [41]:
import numpy as np

# More comprehensive DPG-based dataset (simulated)
dpg_data = {
    "project": [
        "Developing open-source software for sustainable agriculture",
        "Providing digital literacy training in underserved communities",
        "Implementing blockchain solutions for transparent supply chains",
        "Creating AI tools for early disease detection in rural areas",
        "Open data platform for climate change research",
        "Digital identity system for refugees",
        "Renewable energy microgrid for remote villages",
        "Affordable assistive technology for people with disabilities",
        "Online platform connecting small farmers to markets",
        "Satellite imagery analysis for deforestation monitoring"
    ],
    "actual_sdg": [
        "SDG 2", # Zero hunger
        "SDG 4", # Quality education
        "SDG 9", # Industry, Innovation, and Infrastructure (proxy for transparent supply chains)
        "SDG 3", # Good health and well-being
        "SDG 13", # Climate Action (proxy for climate change research)
        "SDG 16", # Peace, Justice, and Strong Institutions (proxy for digital identity)
        "SDG 7", # Affordable and clean energy
        "SDG 10", # Reduced inequalities (proxy for assistive technology)
        "SDG 2", # Zero hunger
        "SDG 15"  # Life on Land
    ]
}

# Expand SDG descriptions for the simulated dataset if new SDGs are introduced
# (Assuming SDG 9, 10, 13, 15, 16 might be new for this expanded dataset)
sdgs.update({
    "SDG 8": "Decent work and economic growth",
    "SDG 9": "Industry, innovation and infrastructure",
    "SDG 10": "Reduced inequalities",
    "SDG 11": "Sustainable cities and communities",
    "SDG 12": "Responsible consumption and production",
    "SDG 13": "Climate action",
    "SDG 14": "Life below water",
    "SDG 15": "Life on land",
    "SDG 16": "Peace, justice and strong institutions",
    "SDG 17": "Partnerships for the goals"
})

# Re-encode sdg_embeddings with the expanded list of SDGs
sdg_texts = list(sdgs.values())
sdg_embeddings = model.encode(sdg_texts)

df_dpg = pd.DataFrame(dpg_data)
df_dpg

                                             project actual_sdg
0  Developing open-source software for sustainabl...      SDG 2
1  Providing digital literacy training in underse...      SDG 4
2  Implementing blockchain solutions for transpar...      SDG 9
3  Creating AI tools for early disease detection ...      SDG 3
4     Open data platform for climate change research     SDG 13
5               Digital identity system for refugees     SDG 16
6     Renewable energy microgrid for remote villages      SDG 7
7  Affordable assistive technology for people wit...     SDG 10
8  Online platform connecting small farmers to ma...      SDG 2
9  Satellite imagery analysis for deforestation m...     SDG 15

In [42]:
# Evaluate with the new DPG dataset
print("\n--- Evaluation on DPG Dataset ---")
evaluate(df_dpg)

--- Evaluation on DPG Dataset ---
Project: Developing open-source software for sustainable agriculture
Predicted Top 3:
  - SDG 11: Sustainable cities and communities (Similarity: 0.2528)
  - SDG 12: Responsible consumption and production (Similarity: 0.1995)
  - SDG 13: Climate action (Similarity: 0.1877)
Actual: SDG 2
--- For accuracy calculation, checking against: ['SDG 11', 'SDG 12', 'SDG 13']
Project: Providing digital literacy training in underserved communities
Predicted Top 3:
  - SDG 4: Quality education (Similarity: 0.3168)
  - SDG 17: Partnerships for the goals (Similarity: 0.1757)
  - SDG 1: No poverty (Similarity: 0.1751)
Actual: SDG 4
--- For accuracy calculation, checking against: ['SDG 4', 'SDG 17', 'SDG 1']
Project: Implementing blockchain solutions for transparent supply chains
Predicted Top 3:
  - SDG 9: Industry, innovation and infrastructure (Similarity: 0.2320)
  - SDG 12: Responsible consumption and production (Similarity: 0.2264)
  - SDG 17: Partnerships for the goals (Similarity: 0.1841)
Actual: SDG 9
--- For accuracy calculation, checking against: ['SDG 9', 'SDG 12', 'SDG 17']
Project: Creating AI tools for early disease detection in rural areas
Predicted Top 3:
  - SDG 6: Clean water and sanitation (Similarity: 0.1498)
  - SDG 15: Life on land (Similarity: 0.1233)
  - SDG 11: Sustainable cities and communities (Similarity: 0.1185)
Actual: SDG 3
--- For accuracy calculation, checking against: ['SDG 6', 'SDG 15', 'SDG 11']
Project: Open data platform for climate change research
Predicted Top 3:
  - SDG 13: Climate action (Similarity: 0.4827)
  - SDG 11: Sustainable cities and communities (Similarity: 0.2157)
  - SDG 7: Affordable and clean energy (Similarity: 0.1843)
Actual: SDG 13
--- For accuracy calculation, checking against: ['SDG 13', 'SDG 11', 'SDG 7']
Project: Digital identity system for refugees
Predicted Top 3:
  - SDG 5: Gender equality (Similarity: 0.2312)
  - SDG 16: Peace, justice and strong institutions (Similarity: 0.1488)
  - SDG 17: Partnerships for the goals (Similarity: 0.1457)
Actual: SDG 16
--- For accuracy calculation, checking against: ['SDG 5', 'SDG 16', 'SDG 17']
Project: Renewable energy microgrid for remote villages
Predicted Top 3:
  - SDG 7: Affordable and clean energy (Similarity: 0.4127)
  - SDG 11: Sustainable cities and communities (Similarity: 0.3367)
  - SDG 12: Responsible consumption and production (Similarity: 0.1565)
Actual: SDG 7
--- For accuracy calculation, checking against: ['SDG 7', 'SDG 11', 'SDG 12']
Project: Affordable assistive technology for people with disabilities
Predicted Top 3:
  - SDG 7: Affordable and clean energy (Similarity: 0.2146)
  - SDG 1: No poverty (Similarity: 0.1982)
  - SDG 17: Partnerships for the goals (Similarity: 0.1821)
Actual: SDG 10
--- For accuracy calculation, checking against: ['SDG 7', 'SDG 1', 'SDG 17']
Project: Online platform connecting small farmers to markets
Predicted Top 3:
  - SDG 17: Partnerships for the goals (Similarity: 0.2693)
  - SDG 9: Industry, innovation and infrastructure (Similarity: 0.2044)
  - SDG 1: No poverty (Similarity: 0.2041)
Actual: SDG 2
--- For accuracy calculation, checking against: ['SDG 17', 'SDG 9', 'SDG 1']
Project: Satellite imagery analysis for deforestation monitoring
Predicted Top 3:
  - SDG 15: Life on land (Similarity: 0.2667)
  - SDG 13: Climate action (Similarity: 0.1916)
  - SDG 6: Clean water and sanitation (Similarity: 0.0845)
Actual: SDG 15
--- For accuracy calculation, checking against: ['SDG 15', 'SDG 13', 'SDG 6']

Top-3 Accuracy: 0.6

In [43]:
import numpy as np

# More comprehensive DPG-based dataset (simulated)
dpg_data = {
    "project": [
        "Developing open-source software for sustainable agriculture",
        "Providing digital literacy training in underserved communities",
        "Implementing blockchain solutions for transparent supply chains",
        "Creating AI tools for early disease detection in rural areas",
        "Open data platform for climate change research",
        "Digital identity system for refugees",
        "Renewable energy microgrid for remote villages",
        "Affordable assistive technology for people with disabilities",
        "Online platform connecting small farmers to markets",
        "Satellite imagery analysis for deforestation monitoring"
    ],
    "actual_sdg": [
        "SDG 2", # Zero hunger
        "SDG 4", # Quality education
        "SDG 9", # Industry, Innovation, and Infrastructure (proxy for transparent supply chains)
        "SDG 3", # Good health and well-being
        "SDG 13", # Climate Action (proxy for climate change research)
        "SDG 16", # Peace, Justice, and Strong Institutions (proxy for digital identity)
        "SDG 7", # Affordable and clean energy
        "SDG 10", # Reduced inequalities (proxy for assistive technology)
        "SDG 2", # Zero hunger
        "SDG 15"  # Life on Land
    ]
}

# Expand SDG descriptions for the simulated dataset if new SDGs are introduced
# (Assuming SDG 9, 10, 13, 15, 16 might be new for this expanded dataset)
sdgs.update({
    "SDG 8": "Decent work and economic growth",
    "SDG 9": "Industry, innovation and infrastructure",
    "SDG 10": "Reduced inequalities",
    "SDG 11": "Sustainable cities and communities",
    "SDG 12": "Responsible consumption and production",
    "SDG 13": "Climate action",
    "SDG 14": "Life below water",
    "SDG 15": "Life on land",
    "SDG 16": "Peace, justice and strong institutions",
    "SDG 17": "Partnerships for the goals"
})

# Re-encode sdg_embeddings with the expanded list of SDGs
sdg_texts = list(sdgs.values())
sdg_embeddings = model.encode(sdg_texts)

df_dpg = pd.DataFrame(dpg_data)
df_dpg

                                             project actual_sdg
0  Developing open-source software for sustainabl...      SDG 2
1  Providing digital literacy training in underse...      SDG 4
2  Implementing blockchain solutions for transpar...      SDG 9
3  Creating AI tools for early disease detection ...      SDG 3
4     Open data platform for climate change research     SDG 13
5               Digital identity system for refugees     SDG 16
6     Renewable energy microgrid for remote villages      SDG 7
7  Affordable assistive technology for people wit...     SDG 10
8  Online platform connecting small farmers to ma...      SDG 2
9  Satellite imagery analysis for deforestation m...     SDG 15

In [44]:
# Evaluate with the new DPG dataset
print("\n--- Evaluation on DPG Dataset ---")
evaluate(df_dpg)

--- Evaluation on DPG Dataset ---
Project: Developing open-source software for sustainable agriculture
Predicted Top 3:
  - SDG 11: Sustainable cities and communities (Similarity: 0.2528)
  - SDG 12: Responsible consumption and production (Similarity: 0.1995)
  - SDG 13: Climate action (Similarity: 0.1877)
Actual: SDG 2
--- For accuracy calculation, checking against: ['SDG 11', 'SDG 12', 'SDG 13']
Project: Providing digital literacy training in underserved communities
Predicted Top 3:
  - SDG 4: Quality education (Similarity: 0.3168)
  - SDG 17: Partnerships for the goals (Similarity: 0.1757)
  - SDG 1: No poverty (Similarity: 0.1751)
Actual: SDG 4
--- For accuracy calculation, checking against: ['SDG 4', 'SDG 17', 'SDG 1']
Project: Implementing blockchain solutions for transparent supply chains
Predicted Top 3:
  - SDG 9: Industry, innovation and infrastructure (Similarity: 0.2320)
  - SDG 12: Responsible consumption and production (Similarity: 0.2264)
  - SDG 17: Partnerships for the goals (Similarity: 0.1841)
Actual: SDG 9
--- For accuracy calculation, checking against: ['SDG 9', 'SDG 12', 'SDG 17']
Project: Creating AI tools for early disease detection in rural areas
Predicted Top 3:
  - SDG 6: Clean water and sanitation (Similarity: 0.1498)
  - SDG 15: Life on land (Similarity: 0.1233)
  - SDG 11: Sustainable cities and communities (Similarity: 0.1185)
Actual: SDG 3
--- For accuracy calculation, checking against: ['SDG 6', 'SDG 15', 'SDG 11']
Project: Open data platform for climate change research
Predicted Top 3:
  - SDG 13: Climate action (Similarity: 0.4827)
  - SDG 11: Sustainable cities and communities (Similarity: 0.2157)
  - SDG 7: Affordable and clean energy (Similarity: 0.1843)
Actual: SDG 13
--- For accuracy calculation, checking against: ['SDG 13', 'SDG 11', 'SDG 7']
Project: Digital identity system for refugees
Predicted Top 3:
  - SDG 5: Gender equality (Similarity: 0.2312)
  - SDG 16: Peace, justice and strong institutions (Similarity: 0.1488)
  - SDG 17: Partnerships for the goals (Similarity: 0.1457)
Actual: SDG 16
--- For accuracy calculation, checking against: ['SDG 5', 'SDG 16', 'SDG 17']
Project: Renewable energy microgrid for remote villages
Predicted Top 3:
  - SDG 7: Affordable and clean energy (Similarity: 0.4127)
  - SDG 11: Sustainable cities and communities (Similarity: 0.3367)
  - SDG 12: Responsible consumption and production (Similarity: 0.1565)
Actual: SDG 7
--- For accuracy calculation, checking against: ['SDG 7', 'SDG 11', 'SDG 12']
Project: Affordable assistive technology for people with disabilities
Predicted Top 3:
  - SDG 7: Affordable and clean energy (Similarity: 0.2146)
  - SDG 1: No poverty (Similarity: 0.1982)
  - SDG 17: Partnerships for the goals (Similarity: 0.1821)
Actual: SDG 10
--- For accuracy calculation, checking against: ['SDG 7', 'SDG 1', 'SDG 17']
Project: Online platform connecting small farmers to markets
Predicted Top 3:
  - SDG 17: Partnerships for the goals (Similarity: 0.2693)
  - SDG 9: Industry, innovation and infrastructure (Similarity: 0.2044)
  - SDG 1: No poverty (Similarity: 0.2041)
Actual: SDG 2
--- For accuracy calculation, checking against: ['SDG 17', 'SDG 9', 'SDG 1']
Project: Satellite imagery analysis for deforestation monitoring
Predicted Top 3:
  - SDG 15: Life on land (Similarity: 0.2667)
  - SDG 13: Climate action (Similarity: 0.1916)
  - SDG 6: Clean water and sanitation (Similarity: 0.0845)
Actual: SDG 15
--- For accuracy calculation, checking against: ['SDG 15', 'SDG 13', 'SDG 6']

Top-3 Accuracy: 0.6

In [45]:
from ipywidgets import Textarea, Button, VBox, Output, Layout
from IPython.display import display

print("### SDG Prediction Interface ###\n")

project_input = Textarea(
    value='',
    placeholder='Enter project description here...',
    description='Project:',
    disabled=False,
    layout=Layout(width='auto', height='100px')
)

predict_button = Button(description="Predict SDG")
output_area = Output()

def on_button_click(b):
    with output_area:
        output_area.clear_output()
        project_description = project_input.value
        if project_description:
            print(f"Analyzing project: '{project_description}'")
            predictions = _predict_sdg_with_details(project_description)
            print("\nPredicted Top 3 SDGs:")
            for sdg_code, sdg_desc, score in predictions:
                print(f"  - {sdg_code}: {sdg_desc} (Similarity: {score:.4f})")
        else:
            print("Please enter a project description.")

predict_button.on_click(on_button_click)

display(VBox([project_input, predict_button, output_area]))

### SDG Prediction Interface ###

VBox(children=(Textarea(value='', description='Project:', layout=Layout(height='100px', width='auto'), placeho…

In [46]:
from ipywidgets import Textarea, Button, VBox, Output, Layout
from IPython.display import display

print("### SDG Prediction Interface ###\n")

project_input = Textarea(
    value='',
    placeholder='Enter project description here...',
    description='Project:',
    disabled=False,
    layout=Layout(width='auto', height='100px')
)

predict_button = Button(description="Predict SDG")
output_area = Output()

def on_button_click(b):
    with output_area:
        output_area.clear_output()
        project_description = project_input.value
        if project_description:
            print(f"Analyzing project: '{project_description}'")
            predictions = _predict_sdg_with_details(project_description)
            print("\nPredicted Top 3 SDGs:")
            for sdg_code, sdg_desc, score in predictions:
                print(f"  - {sdg_code}: {sdg_desc} (Similarity: {score:.4f})")
        else:
            print("Please enter a project description.")

predict_button.on_click(on_button_click)

display(VBox([project_input, predict_button, output_area]))

### SDG Prediction Interface ###

VBox(children=(Textarea(value='', description='Project:', layout=Layout(height='100px', width='auto'), placeho…

In [47]:
correct = 0

for _, row in df.iterrows():
    pred, _ = predict_sdg(row["project"])

    print("Project:", row["project"])
    print("Predicted:", pred)
    print("Actual:", row["actual_sdg"])
    print("---")

    if pred == row["actual_sdg"]:
        correct += 1

accuracy = correct / len(df)

print("Accuracy:", accuracy)

Project: Mobile health app for villages
Predicted: SDG 3
Actual: SDG 3
---
Project: Online education platform for students
Predicted: SDG 4
Actual: SDG 4
---
Project: Clean drinking water system
Predicted: SDG 6
Actual: SDG 6
---
Project: Solar energy for rural homes
Predicted: SDG 7
Actual: SDG 7
---
Accuracy: 1.0